### ISSUE TITLE
"From" in Column names causes database problems

### ISSUE THREAD

**Issue by karynne7** [ImperialCardioGenetics/uORFs#1]
I can get around the issue by editing my VEP header in the VCF before loading into a db (I'm using Gemini). However, I think you should rename your column headers not to have special functions in the schema. (i.e. uAUG_DistanceFromCap could be uAUG_DistanceFrmCap) Thanks!

**Comment by XiaoleiZ** [comment]
Thanks for the suggestion. We've updated it.
